#!/bin/bash

###
# Use to run xspider module
# Usage: ./run help
##

# WORKDIR = "./"


function all()
{
    python manage.py run all
}

function background()
{
    python manage.py run background
}

function web()
{
    python manage.py run web
}

function flower()
{
    python manage.py run flower
    # celery -A xspider flower
}

function generator()
{
    python manage.py run generator
	# celery worker --app=xspider -l info -n worker1@%h -Q low-generator
}

function processor()
{
    python manage.py run processor
    # celery worker --app=xspider -l info -n worker2@%h -Q low-processor

}

function scheduler()
{
    python manage.py run scheduler
}

function usage()
{
   echo "Usage: ./run {all/web/background/flower/generator/processor/scheduler}"
   echo ""
   echo "        all:         Run xspider all modules"
   echo "        web:         Run xspider web module"
   echo "        background:  Run xspider background scheduler/generator/processor"
   echo "        scheduler:   Run xspider scheduler"
   echo "        flower:      Run xspider celery flower module"
   echo "        generator:   Run xspider generator celery worker"
   echo "        processor:   Run xspider processor celery worker"
   echo ""
}

main()
{
	#file="/tmp/$1.lock"
	#(
	#    flock -xn -w 10 200 || exit 1

        case $1 in
            "web")
            	web
            ;;
            "flower")
            	flower
            ;;
            "generator")
                generator
            ;;
            "processor")
            	processor
            ;;
            "scheduler")
            	scheduler
            ;;
            "all")
            	all
            ;;
            "background")
            	background
            ;;
            *)
            	usage
            ;;
            help)
            	usage
            ;;
            esac

	#) 200>${file}	
}

main $*
