"""
Django settings for xspider project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import redis
from common import *


# Spiders Path
PROJECTS_PTAH = os.path.join(os.path.dirname(BASE_DIR), "projects")

# Execute Path
EXECUTE_PATH = os.path.join(BASE_DIR, "execute")

# Redis Settings
REDIS_IP = 'localhost'
REDIS_PORT = '6379'
REDIS_POOL = redis.ConnectionPool(host=REDIS_IP, port=REDIS_PORT)

# Mongodb settings
MongoDBS = {
    'xspider_project': {
        'host': 'mongodb://localhost/xspider_project',
    },
    'xspider_task': {
        'host': 'mongodb://localhost/xspider_task',
    },
    'xspider_result': {
        'host': 'mongodb://localhost/xspider_result',
    }
}

from mongoengine import connect  # noqa

for name, db in MongoDBS.iteritems():
    connect(host=db['host'], alias=name)


# Celery settings

BROKER_URL = 'amqp://guest:guest@localhost//'

#: Only add pickle to this list if your broker is secured
#: from unwanted access (see userguide/security.html)

# BROKER_URL = 'amqp://'
CELERY_RESULT_BACKEND = 'amqp://'

CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = 'Europe/Oslo'
CELERY_ENABLE_UTC = True

# CELERY_ROUTES = {
#          'tasks.add': 'low-priority',
#
#  }

CELERY_ANNOTATIONS = {
    'xworker.tasks.generator': {'rate_limit': '60/m'},
    'xworker.tasks.processor': {'rate_limit': '60/m'},
    'xworker.tasks.add': {'rate_limit': '6/m'},
    # 'xworker.task1.enterprise': {'rate_limit': '6/m'}

}

CELERY_IMPORTS = (
    'xworker.tasks',
)


