"""
Django settings for xspider project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from common import *


# Spiders Path
PROJECTS_PTAH = os.path.join(os.path.dirname(BASE_DIR), "projects")

# Execute Path
EXECUTE_PATH = os.path.join(BASE_DIR, "execute")

# Mongodb settings
MongoDBS = {
    'xspider_project': {
        'host': 'mongodb://localhost/xspider_project',
    },
    'xspider_task': {
        'host': 'mongodb://localhost/xspider_task',
    },
    'xspider_result': {
        'host': 'mongodb://localhost/xspider_result',
    }
}

from mongoengine import connect  # noqa

for name, db in MongoDBS.iteritems():
    connect(host=db['host'], alias=name)

REDIS_URL = 'localhost:6379'